//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plantilla.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.AuthorXBook = new HashSet<AuthorXBook>();
        }
    
        public int Id { get; set; }
        public int GenericDocumentId { get; set; }
        public string BookName { get; set; }
        public int EditorialId { get; set; }
        public System.DateTime PublicationDate { get; set; }
        public string PublicationURL { get; set; }
        public bool IsDeleted_ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuthorXBook> AuthorXBook { get; set; }
        public virtual Editorial Editorial { get; set; }
        public virtual GenericDocument GenericDocument { get; set; }
    }
}
