//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plantilla.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollegeDegreeDocuments
    {
        public int Id { get; set; }
        public int GenericDocumentId { get; set; }
        public int CollegeDegreeTypeId { get; set; }
        public int Year { get; set; }
        public int InstitutionId { get; set; }
        public int CountryId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual CollegeDegreeTypes CollegeDegreeTypes { get; set; }
        public virtual Countries Countries { get; set; }
        public virtual GenericDocument GenericDocument { get; set; }
        public virtual Institutions Institutions { get; set; }
    }
}
