//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plantilla.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageKnowledgeDocuments
    {
        public int Id { get; set; }
        public int GenericDocumentId { get; set; }
        public int LanguageId { get; set; }
        public int CertifyingBoydId { get; set; }
        public int Year { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual CertifyingBody CertifyingBody { get; set; }
        public virtual GenericDocument GenericDocument { get; set; }
        public virtual Languages Languages { get; set; }
    }
}
