//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plantilla.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MagazinesArticles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MagazinesArticles()
        {
            this.AuthorXArticle = new HashSet<AuthorXArticle>();
        }
    
        public int Id { get; set; }
        public int GenericDocumentId { get; set; }
        public string ArticleName { get; set; }
        public int MagazineId { get; set; }
        public System.DateTime PublicationDate { get; set; }
        public string PublicationUrl { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual GenericDocument GenericDocument { get; set; }
        public virtual Magazines Magazines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuthorXArticle> AuthorXArticle { get; set; }
    }
}
