//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plantilla.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MagazinesArticles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MagazinesArticles()
        {
            this.AuthorXArticle = new HashSet<AuthorXArticle>();
        }
    
        public int Id { get; set; }
        public int GenericDocumentId { get; set; }
        public string ArticleName { get; set; }
        public int MagazineId { get; set; }
        public System.DateTime PublicationDate { get; set; }
        public string PublicationUrl { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual GenericDocument GenericDocument { get; set; }
        public virtual Magazines Magazines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuthorXArticle> AuthorXArticle { get; set; }
    }
}
