//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plantilla.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public int Id { get; set; }
        public int GenericDocumentId { get; set; }
        public string Name { get; set; }
        public System.DateTime TrainingStarDate { get; set; }
        public System.DateTime TrainingEndDate { get; set; }
        public int TrainingHours { get; set; }
        public int TrainingEntityId { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual GenericDocument GenericDocument { get; set; }
        public virtual TrainingEntities TrainingEntities { get; set; }
    }
}
