//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plantilla.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public int Id { get; set; }
        public int GenericDocumentId { get; set; }
        public string Name { get; set; }
        public System.DateTime TrainingStarDate { get; set; }
        public System.DateTime TrainingEndDate { get; set; }
        public int TrainingHours { get; set; }
        public int TrainingEntityId { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual GenericDocument GenericDocument { get; set; }
        public virtual TrainingEntities TrainingEntities { get; set; }
    }
}
