//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plantilla.UIProcess.WCF_ServicioPlantilla {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF_ServicioPlantilla.IServiciosPlantilla")]
    public interface IServiciosPlantilla {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosPlantilla/ConsultarConfiguracion", ReplyAction="http://tempuri.org/IServiciosPlantilla/ConsultarConfiguracionResponse")]
        Plantilla.Objetos.Clases.oRespuesta<System.Collections.Generic.List<Plantilla.Objetos.Clases.Configuracion>> ConsultarConfiguracion(System.Nullable<int> idConfiguracion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosPlantilla/ConsultarConfiguracion", ReplyAction="http://tempuri.org/IServiciosPlantilla/ConsultarConfiguracionResponse")]
        System.Threading.Tasks.Task<Plantilla.Objetos.Clases.oRespuesta<System.Collections.Generic.List<Plantilla.Objetos.Clases.Configuracion>>> ConsultarConfiguracionAsync(System.Nullable<int> idConfiguracion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiciosPlantillaChannel : Plantilla.UIProcess.WCF_ServicioPlantilla.IServiciosPlantilla, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosPlantillaClient : System.ServiceModel.ClientBase<Plantilla.UIProcess.WCF_ServicioPlantilla.IServiciosPlantilla>, Plantilla.UIProcess.WCF_ServicioPlantilla.IServiciosPlantilla {
        
        public ServiciosPlantillaClient() {
        }
        
        public ServiciosPlantillaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosPlantillaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosPlantillaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosPlantillaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Plantilla.Objetos.Clases.oRespuesta<System.Collections.Generic.List<Plantilla.Objetos.Clases.Configuracion>> ConsultarConfiguracion(System.Nullable<int> idConfiguracion) {
            return base.Channel.ConsultarConfiguracion(idConfiguracion);
        }
        
        public System.Threading.Tasks.Task<Plantilla.Objetos.Clases.oRespuesta<System.Collections.Generic.List<Plantilla.Objetos.Clases.Configuracion>>> ConsultarConfiguracionAsync(System.Nullable<int> idConfiguracion) {
            return base.Channel.ConsultarConfiguracionAsync(idConfiguracion);
        }
    }
}
